# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: onecorp
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: luxswipe
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ls

provider:
  name: aws
  runtime: python3.12

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: any
          cors:
            allowedOrigins:
              - http://localhost:3000
              - https://www.luxswipe.in
            allowedHeaders:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
